# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Camposphere
                                 A QGIS plugin
 Premet d'extraire les batiments modulaire dans une parcelle cadastrale
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-13
        copyright            : (C) 2026 by Lisa Verrier & Daouda Timera
        email                : lisa.verrier04@gmail.com, timeradaouda5@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Camposphere class from file Camposphere.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .extract_bat_modulaire import Camposphere
    return Camposphere(iface)
