# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Camposphere
                                 A QGIS plugin
 Premet d'extraire les batiments modulaire dans une parcelle cadastrale
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-13
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Lisa Verrier & Daouda Timera
        email                : lisa.verrier04@gmail.com, timeradaouda5@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import *

from qgis.core import* # QgsVectorLayer,QgsRasterLayer, QgsProject, QgsField,QgsCoordinateTransform, QgsCoordinateReferenceSystem,QgsPointXY, QgsDistanceArea

import processing


#Le code de traitement situé dans ce dossier 
from .traitement_cadastre import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .extract_bat_modulaire_dialog import CamposphereDialog
import os.path
import skimage
import numpy as np
from osgeo import gdal, osr
import psycopg2



class Camposphere:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Camposphere_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Extraction Batiment Modulaire')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Camposphere', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/extract_bat_modulaire/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Séléction des BM'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Extraction Batiment Modulaire'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CamposphereDialog()

         # ******************** création de signal de cponnexion ********************************
            self.dlg.boutonVAdresse.clicked.connect(self.load_csv_Adresse)
            self.dlg.boutonVBM.clicked.connect(self.load_shapefile_BM)
            
            self.dlg.boutonLancement.clicked.connect(self.traitement)


        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
    
    # ********************* Fonction pour charger un shapefile lorsque le boutonVBM est cliqué ************************

    def load_shapefile_BM(self):
        file_dialog = QFileDialog()
        file_dialog.setFileMode(QFileDialog.FileMode.ExistingFiles)
        file_dialog.setNameFilter("Shapefiles (*.shp)")
        file_dialog.setViewMode(QFileDialog.ViewMode.List)

        if file_dialog.exec():
            file_paths = file_dialog.selectedFiles()
            if file_paths:
                file_path = file_paths[0]
                self.dlg.lineBM.setText(file_path)  # Mets à jour l'UI
                if self.initialise_BM():  # Appelle la nouvelle fonction
                    QgsProject.instance().addMapLayer(self.bm)
                    QMessageBox.information(None, "Chargement réussi", f"Fichier chargé avec {self.bm.featureCount()} objets géométriques.")

    # ********************* Fonction pour charger un shapefile lorsque le boutonVAdresse est cliqué ************************

    def load_csv_Adresse(self):
        file_dialog = QFileDialog()
        file_dialog.setFileMode(QFileDialog.FileMode.ExistingFiles)
        file_dialog.setNameFilter("Valeurs séparées par une virgule (*.csv);;Shapefiles (*.shp)")
        file_dialog.setViewMode(QFileDialog.ViewMode.List)

        if file_dialog.exec():
            file_paths = file_dialog.selectedFiles()
            if file_paths:
                file_path = file_paths[0]
                self.dlg.lineAdresse.setText(file_path)  # Mets à jour l'UI
                if self.initialise_Adresse():  # Appelle la nouvelle fonction
                    QgsProject.instance().addMapLayer(self.adresse)
                    QMessageBox.information(None, "Chargement réussi", f"Fichier chargé avec {self.adresse.featureCount()} objets géométriques.")

    # ********************* Fonction pour mettre à jour BM ************************
    
    def initialise_BM(self):
        file_path = self.dlg.lineBM.text()
        if os.path.exists(file_path):
            try:
                layer_name = os.path.splitext(os.path.basename(file_path))[0]
                layer = QgsVectorLayer(file_path, layer_name, "ogr")

                if not layer.isValid():
                    raise Exception("La couche n'est pas valide.")

                # Initialise la variable bm
                self.bm = layer
                
                return True  # Succès
            except Exception as e:
                QMessageBox.critical(None, "Erreur", f"Erreur lors de l'initialisation de la couche : {str(e)}")
                return False
        else:
            QMessageBox.warning(None, "Chemin invalide", "Le fichier spécifié n'existe pas.")
            return False

    # ********************* Fonction pour mettre à jour Adresse ************************
    
    def initialise_Adresse(self):
        file_path = self.dlg.lineAdresse.text()
        if os.path.exists(file_path):
            try:
                layer_name = os.path.splitext(os.path.basename(file_path))[0]
                layer = QgsVectorLayer(file_path, layer_name, "ogr")

                if not layer.isValid():
                    raise Exception("La couche n'est pas valide.")

                # Initialise la variable adresse
                self.adresse = layer
                
                return True  # Succès
            except Exception as e:
                QMessageBox.critical(None, "Erreur", f"Erreur lors de l'initialisation de la couche : {str(e)}")
                return False
        else:
            QMessageBox.warning(None, "Chemin invalide", "Le fichier spécifié n'existe pas.")
            return False

        # ********************* Fonction pour démarrer les traitements ************************

    def traitement(self):
        #faut que je vérifie si self. bm et self.adresse existe
        QMessageBox.information(None, "Echec du traitement", f"Le code de traitement n'existe pas encore :,(")
        processing.run("script:Selection BM selon adresse", {'bm': self.bm ,'input_points': self.adresse ,'parcelles_cadastrales':"WFS://pagingEnabled='default' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:3857' typename='CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle' url='https://data.geopf.fr/wfs/' version='auto'",'Parcelles_selec':'C:/Users/Formation/Desktop/PDI/travail_encours/donnees-test/donnees_test.gpkg','Bm_adresse_selec':'C:/Users/Formation/Desktop/PDI/travail_encours/donnees-test/donnees_test2.gpkg'})